{% set name = "atsim-potentials" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/atsim.potentials/atsim.potentials-{{ version }}.tar.gz
  sha256: 0c3e4e2323e969880f17a9924642e0991be5761f50b254bcbadd046db3be6390

build:
  number: 0
  noarch: python
  entry_points:
    - potable=atsim.potentials.tools.potable:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cexprtk >=0.3.4
    - configparser
    - future
    - openpyxl >=3.0.0
    - pyparsing >=2.2.0
    - python >=3.6
    - scipy
    - setuptools
    - wrapt ==1.11.2

test:
  imports:
    - atsim
    - atsim.potentials
  commands:
    - pip check
    - potable --help
  requires:
    - pip

about:
  home: https://github.com/mjdrushton/atsim-potentials
  license: Apache-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: Tools and python module to assist in tabulation of pair and EAM potentials for atomistic simulation.
  description: |
    Classical simulation codes typically contain a good selection of
    analytical forms for describing atomic interactions. Sometimes
    however, you may need to use a potential that is not directly
    supported by the code. Luckily, most simulation codes allow you to
    provide tabulated potentials in which energies and forces, for a
    range of interatomic separations, are pre-calculated and specified as
    rows within a text file. The atsim.potentials package provides python
    modules to make the specification and tabulation of pair- and
    many-body potentials straightforward and consistent.
  doc_url: https://atsimpotentials.readthedocs.io
  dev_url: https://github.com/mjdrushton/atsim-potentials

extra:
  recipe-maintainers:
    - jan-janssen
